# Set architecture flags
export ARCHFLAGS="-arch x86_64"

# Add bash completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

# Update the Path
export PATH=/usr/local/share/npm/bin:$HOME/.rbenv/bin:/usr/local/bin:/usr/local/sbin:$PATH

# Initialize rbenv
eval "$(rbenv init -)"

# Set Node Path for NPM
export NODE_PATH=/usr/local/lib/node_modules

export GREP_OPTIONS='--color=auto'
export CLICOLOR=1

# Set my preferred editor
export VISUAL='mvim -v'
export EDITOR='mvim -v'

# Virtualenv setup stuff
if [ -f /usr/local/share/python/virtualenvwrapper.sh ]; then
    [ -d $HOME/sites/env ] || mkdir -p $HOME/sites/env
    export WORKON_HOME="$HOME/sites/env"
    source /usr/local/share/python/virtualenvwrapper.sh

    # virtualenv stuff
#    export VIRTUALENV_USE_DISTRIBUTE=true

    # pip stuff
    export PIP_VIRTUALENV_BASE=$WORKON_HOME
    export PIP_REQUIRE_VIRTUALENV=true
    export PIP_RESPECT_VIRTUALENV=true
    export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
fi

# Source the .bashrc if one exists
if [ -f ~/.bashrc ] && ! shopt -oq posix; then
    . ~/.bashrc
fi
